### ISSUE TITLE
Update the Login System to integrate Organizations

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-userportal#13]
The Login System will now need to know which Organization the user wishes to login too.  The Login will need to be updated to reflect this change.

**Comment by robjansen15** [comment]
I don't agree this is a high priority for this sprint. We should assume one organization for now.

**Comment by DannyPeck** [comment]
This issue has actually been depreciated by the refactor login to use email address.  If each user has a unique email address the backend can programmatically determine which organization the user belongs to and remove the need for this information the frontend.
