### ISSUE TITLE
Integrate the passport-local strategy to perform the authentication

### ISSUE THREAD

**Issue by robjansen15** [CS450-ECE461/fall2016-group2-userportal#15]
In order to login all that needs to happen is the users session needs to be created, the access_token must be stored in the session and they must be redirected to the loggedin page.

We will be using the passport node module which allows for integrating authentication into your service.  It follows the Strategy Pattern by allowing you to choose the authentication strategy you wish to use.  We will be using the passport-local strategy which focuses on only using username and password.

Here is the documentation for [passport](https://github.com/jaredhanson/passport)
Here is the documentation for [passport-local](https://github.com/jaredhanson/passport-local)
Here is the [tutorial](https://github.com/onehilltech/blueprint/wiki/Tutorials:Authentication:Session) listed by Dr. Hill.

Parts of this tutorial are obsolete due to the way we have designed our system.  All direct calls to the User Model are obsolete.  You will replace this with the code to login with the backend api and storing the token in the session.

**Comment by DannyPeck** [comment]
Isn't this logout?  I have a issue for this ;)

**Comment by robjansen15** [comment]
I copied your wording, but I think we need to create the session and save it to mongo OR use passport.

**Comment by DannyPeck** [comment]
Right, so this issue should said that, the message you copied is for logout haha :D
